#!/bin/bash

shopt -s nocasematch
read -sn 10000 -t 0.1
read -srn 1 input
if [[ "$input" =~ [1-4rsgqwe] ]]; then
  echo -n "$input"
elif [[ $(echo -e "$input" | od -t x | grep "1b") ]]; then
  read -srn 6 input
  if [[ "${input:5}" =~ [1-4rsgqwe] ]]; then
    echo -n "${input:5}"
  else
    read -sd M -t 0.001
    read -srn 3 -t 0.001 click
    echo -n "${click:(-2)}"
  fi
fi
