#!/bin/bash

read -srN 1 input
read -srt 0.00005 cursor
if [[ -z "$cursor" && "$input" =~ [1-4SGQWEsgqwe] ]]; then
  echo -n "$input"
elif [[ $(echo -e "$input" | od -t x | grep "1b") ]]; then
  echo -n "$input$cursor"
else
  read -sn 1000 -t 0.0002
fi
